env: game24

method: xot  

task:  
  data: data/game24/game24_test.csv  
  total_game_step: 3  
  task_start_index: 0  
  task_end_index: 2 
  
gpt:  
  backend: custom
  temperature: 0.0  
  stop: None    
  
param:
  n_generate_sample: 1  
  n_evaluate_sample: None 
  n_select_sample: None 
  last_step: 1 # 表示是否包含思考的最后一步 (1) 或不包含 (0)
  
multi_solution: 0  
  
xot:  
  numMCTSSims: 200  
  multi_numMCTSSims: 500  
  multi_solution_exploration: 500 
  
  revised: 1  # 表示是否允许修订 (1) 或不允许 (0)
  revise_times: 1  # 修订次数
  revise_total_game_step: 3  
  revise_numMCTSSims: 500  
  
model:  
  checkpoint: ./temp/game24
  filename: best.pth.tar
  cpuct: 1
